nao_core_home:
    path: /
    defaults: { _controller: NAOCoreBundle:Core:home }

nao_core_about:
    path: /about
    defaults: { _controller: NAOCoreBundle:Core:about }

nao_core_contact:
    path: /contact
    defaults: { _controller: NAOCoreBundle:Core:contact }
