<?php

namespace NAO\BirdBundle\Repository;

/**
 * AvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNomVernAndFamille()
	{
		$query = $this->_em->createQuery('SELECT a.id, a.nomVern, a.famille FROM NAOBirdBundle:Aves a WHERE a.nomVern != :param  AND a.famille != :param ORDER BY a.nomVern ASC');

		$query->setParameter(':param', '');

		$results = $query->getResult();

		return $results;
	}
}
