<?php

namespace NAO\BirdBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getListBySpecies($value)
	{
		$query = $this->_em->createQuery('SELECT o.birdname, o.species FROM NAOBirdBundle:Observation o WHERE o.species LIKE :species AND o.validated = :validated ORDER BY o.species ASC');

		$query->setParameter(':species', '%' . $value . '%');

		$query->setParameter(':validated', true);

		$results = $query->getResult();

		return $results;
	}

	public function getListByBirdname($value)
	{
		$query = $this->_em->createQuery('SELECT o.birdname, o.species FROM NAOBirdBundle:Observation o WHERE o.birdname LIKE :birdname AND o.validated = :validated ORDER BY o.species ASC');

		$query->setParameter(':birdname', '%' . $value . '%');

		$query->setParameter(':validated', true);

		$results = $query->getResult();

		return $results;
	}

	public function getSpeciesValidated($species)
	{
		$query = $this->_em->createQuery('SELECT o FROM NAOBirdBundle:Observation o WHERE o.species LIKE :species AND o.validated = :validated');

		$query->setParameter(':species', '%' . $species . '%');

		$query->setParameter(':validated', true);

		$results = $query->getResult();

		return $results;
	}
}
